services:
  - type: web
    name: nyc-usopen-2026
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /sw.js
        name: Cache-Control
        value: no-cache
